# Data Cleaning Challenges

### Fill missing values appropriately.

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df=pd.read_csv("EV.csv")
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,7.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,37.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,23.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,2.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10

In [7]:
null=df.isnull()
print("There are missing values: ",null)

There are missing values:          VIN (1-10)  County   City  State  Postal Code  Model Year   Make  \
0            False   False  False  False        False       False  False
1            False   False  False  False        False       False  False
2            False   False  False  False        False       False  False
3            False   False  False  False        False       False  False
4            False   False  False  False        False       False  False
...            ...     ...    ...    ...          ...         ...    ...
279775       False   False  False  False        False       False  False
279776       False   False  False  False        False       False  False
279777       False   False  False  False        False       False  False
279778       False   False  False  False        False       False  False
279779       False   False  False  False        False       False  False

        Model  Electric Vehicle Type  \
0       False                  False
1       False                  False
2       False                  False
3       False                  False
4       False                  False
...       ...                    ...
279775  False                  False
279776  False                  False
279777  False                  False
279778  False                  False
279779  False                  False

        Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0                                                   False           False
1                                                   False           False
2                                                   False           False
3                                                   False           False
4                                                   False           False
...                                                   ...             ...
279775                                              False           False
279776                                              False           False
279777                                              False           False
279778                                              False           False
279779                                              False           False

        Legislative District  DOL Vehicle ID  Vehicle Location  \
0                      False           False             False
1                      False           False             False
2                      False           False             False
3                      False           False             False
4                      False           False             False
...                      ...             ...               ...
279775                 False           False             False
279776                 False           False             False
279777                 False           False             False
279778                 False           False             False
279779                 False           False             False

        Electric Utility  2020 Census Tract
0                  False              False
1                  False              False
2                  False              False
3                  False              False
4                  False              False
...                  ...                ...
279775             False              False
279776             False              False
279777             False              False
279778             False              False
279779             False              False

[279780 rows x 16 columns]

### Remove unnecessary columns

In [9]:
df.drop(columns="Legislative District")

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279775,3GPKHXRJ8R,Clark,Washougal,WA,98671.0,2024,HONDA,PROLOGUE,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,276754432,POINT (-122.35341 45.57923),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
279776,WBY8P8C51K,King,Seattle,WA,98103.0,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,280708333,POINT (-122.35436 47.67596),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
279777,7PDSGCBA3T,King,Sammamish,WA,98075.0,2026,RIVIAN,R1S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,286565541,POINT (-122.03539 47.61344),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
279778,7SAYGDED2T,Pierce,Bonney Lake,WA,98391.0,2026,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,288480419,POINT (-122.17144 47.19175),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10
279779,3GNKDCRJ2R,Pierce,Graham,WA,98338.0,2024,CHEVROLET,BLAZER,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,267728625,POINT (-122.29477 47.05703),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10

### Rename columns to cleaner names

In [11]:
df.rename(columns={"Model Year": "Model_Year",
    "Electric Vehicle Type": "EV_Type",
    "Electric Range": "Electric_Range",
    "Base MSRP": "Base_MSRP",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "CAFV_Eligibility",
    "Vehicle Location": "Vehicle_Location",
    "Electric Utility": "Electric_Utility",
    "Legislative District": "Legislative_District",
    "Postal Code": "Postal_Code",
    "County": "County",
    "State": "State",
    "City": "City",
    "Make": "Make",
    "Model": "Model"})

,VIN (1-10),County,City,State,Postal_Code,Model_Year,Make,Model,EV_Type,CAFV_Eligibility,Electric_Range,Legislative_District,DOL Vehicle ID,Vehicle_Location,Electric_Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,7.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,37.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,23.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,2.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279775,3GPKHXRJ8R,Clark,Washougal,WA,98671.0,2024,HONDA,PROLOGUE,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,18.0,276754432,POINT (-122.35341 45.57923),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
279776,WBY8P8C51K,King,Seattle,WA,98103.0,2019,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,126.0,36.0,280708333,POINT (-122.35436 47.67596),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
279777,7PDSGCBA3T,King,Sammamish,WA,98075.0,2026,RIVIAN,R1S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,41.0,286565541,POINT (-122.03539 47.61344),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
279778,7SAYGDED2T,Pierce,Bonney Lake,WA,98391.0,2026,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,31.0,288480419,POINT (-122.17144 47.19175),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10
279779,3GNKDCRJ2R,Pierce,Graham,WA,98338.0,2024,CHEVROLET,BLAZER,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,2.0,267728625,POINT (-122.29477 47.05703),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10